export enum RUNNER_EVENT {
  START = "START",
  COMPLETED = "COMPLETED",
  ERROR = "ERROR",

  STEP_DONE = "STEP_DONE",
  STEP_BEGIN = "STEP_DONE",

  PARSED = "PARSED",
  CONSOLE = "CONSOLE",
  TASK_OVERVIEW = "TASK_OVERVIEW",
  TASK_BEGIN = "TASK_BEGIN",
  TASK_DONE = "TASK_DONE",
}
